### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by skydark** [HenryLoenwind/EnderIOAddons#22]
Game crashed while starting up (See http://pastebin.com/P3SiFdem for full log):

```
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
        at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
......
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
        at info.loenwind.enderioaddons.timer.Celeb11.<init>(Celeb11.java:80)
        at info.loenwind.enderioaddons.timer.Celeb11.create(Celeb11.java:24)
        at info.loenwind.enderioaddons.EnderIOAddons.init(EnderIOAddons.java:83)
......
```

It seems that you use scala's array instead of java's in https://github.com/HenryLoenwind/EnderIOAddons/blob/master/src/main/java/info/loenwind/enderioaddons/timer/Celeb11.java#L13 .

**Comment by BBoldt** [comment]
People are experiencing this in my modpack as well:
https://www.reddit.com/r/MinecraftUnabridged/comments/3x0kij/suddenly_client_keeps_crashing/

**Comment by RedeyeTheGoblin** [comment]
I'm also getting this, however, I found a workaround - I changed my system clock to 11:30 (GMT), and the error disappeared, so that may help. Not sure what the exact bounds are so some experimentation may be necessary till a fix is introduced...

**Comment by quentfr21** [comment]
i just put a pull request to fix that

@skydark yes it's just a wrong import

e3a9f5526cca9effa2c938eb52fb87c0f0cd24bf

**Comment by HenryLoenwind** [comment]
Just upgrade, the fixed version is live.

Sry, quentfr21, someone pinged me on IRC before I saw this.

**Comment by tterrag1098** [comment]
This is why I blacklisted scala.\* from my imports ages ago :P

**Comment by HenryLoenwind** [comment]
ok, how do I do that?
