### ISSUE TITLE
Incompatible with Agricraft 1.4.6

### ISSUE THREAD

**Issue by Rukachan** [HenryLoenwind/EnderIOAddons#25]
```
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantAPIv1.tier(CropPlantAPIv1.java:33)
    at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlant.<init>(CropPlant.java:40)
    at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantAPIv1.<init>(CropPlantAPIv1.java:27)
    at com.InfinityRaider.AgriCraft.apiimpl.v1.APIimplv1.registerCropPlant(APIimplv1.java:108)
    at info.loenwind.enderioaddons.machine.afarm.TileAfarm.registerPlants(TileAfarm.java:129)
    at info.loenwind.enderioaddons.machine.afarm.AgriDetector.registerPlants(AgriDetector.java:29)
    at info.loenwind.enderioaddons.proxy.ClientAndServerProxy.init(ClientAndServerProxy.java:60)
    at info.loenwind.enderioaddons.proxy.ClientOnlyProxy.init(ClientOnlyProxy.java:76)
    at info.loenwind.enderioaddons.EnderIOAddons.init(EnderIOAddons.java:69)
```

**Comment by therealericbj** [comment]
I'm experiencing the same issue.

Started client, got this...

http://openeye.openmods.info/crashes/d2fd59606e6ca57d6b760173d19d231e

**Comment by wasweb** [comment]
Solved: https://github.com/InfinityRaider/AgriCraft/issues/517

**Comment by HenryLoenwind** [comment]
I love it when the only bugs that come in on my slow day are ones that get handled by other people. Thanks for posting it in both places.
